Repository submariner-io/admiral, pull requests merged in 2021-08, with the labels that each got.

#260 Don't run periodic PR dependency checks on forks
  .github/workflows/dependent-issues.yml
Labels: automation

#265 Retract 0.10.0
  go.mod
Labels: backport

#267 Use same issue-create GHA as most SubM CI
  .github/workflows/periodic.yml
Labels: automation

#266 Fix YAML linting errors
  .github/dependabot.yml
  .github/workflows/dependent-issues.yml
  .golangci.yml
Labels: bug, automation

#270 Remove non-functional yamllint strict config
  .yamllint.yml
Labels: automation

#272 Update create-issue-from-file GHA 2.3.2 to 3.0.0
  .github/workflows/flake_finder.yml
  .github/workflows/periodic.yml
Labels: dependencies, automation
