Repository submariner-io/admiral, pull requests merged in 2021-05, with the labels that each got.

#220 Don't run certain GHA jobs on forks
  .github/workflows/flake_finder.yml
  .github/workflows/periodic.yml
Labels: automation

#221 Add CII badge, remove PR-triggered badges
  README.md
Labels: cncf, documentation

#223 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, documentation, ready-to-test

#224 Update the copyright statements to match CNCF recs
  .github/workflows/linting.yml
  .legal.json
  .licenserc.json
  pkg/fake/delete_colection_reactor.go
  pkg/fake/dynamic_client.go
  pkg/fake/failing_reactor.go
  pkg/federate/cluster_informer.go
  pkg/federate/fake/federator.go
  pkg/federate/federator.go
  pkg/gomega/matchers.go
  pkg/log/loglevels.go
  pkg/resource/dynamic.go
  pkg/resource/interface.go
  pkg/resource/kubernetes.go
  pkg/resource/rest.go
  pkg/resource/util.go
  pkg/stringset/stringset.go
  pkg/stringset/stringset_test.go
  pkg/syncer/broker/broker_suite_test.go
  pkg/syncer/broker/config.go
  pkg/syncer/broker/federator.go
  pkg/syncer/broker/federator_test.go
  pkg/syncer/broker/syncer.go
  pkg/syncer/broker/syncer_test.go
  pkg/syncer/resource_syncer.go
  pkg/syncer/resource_syncer_test.go
  pkg/syncer/syncer.go
  pkg/syncer/syncer_suite_test.go
  pkg/syncer/test/util.go
  pkg/util/create_or_update.go
  pkg/util/create_or_update_test.go
  pkg/util/helpers.go
  pkg/util/util_suite_test.go
  pkg/watcher/resource_watcher.go
  pkg/watcher/resource_watcher_test.go
  pkg/watcher/watcher_suite_test.go
  pkg/workqueue/queue.go
  test/apis/admiral.submariner.io/v1/doc.go
  test/apis/admiral.submariner.io/v1/register.go
  test/apis/admiral.submariner.io/v1/types.go
  test/e2e/e2e_test.go
  test/e2e/syncer/broker.go
  test/e2e/util/util.go
  test/e2e/watcher/watcher.go
Labels: cncf, ready-to-test

#225 Add TryAppendCondition helper function
  pkg/util/condition.go
  pkg/util/condition_test.go
Labels: ready-to-test
