Repository submariner-io/admiral, pull requests merged in 2023-04, with the labels that each got.

#595 Automated backport of #594: Retain status fields when UpdateStatus returns NotFound
  pkg/util/create_or_update.go
  pkg/util/create_or_update_test.go
Labels: automated-backport

#599 AwaitStopped should do just that
  pkg/syncer/resource_syncer.go
  pkg/workqueue/queue.go
Labels: backport

#601 Automated backport of #599: AwaitStopped should do just that
  pkg/syncer/resource_syncer.go
  pkg/workqueue/queue.go
Labels: automated-backport

#603 Fix data race in zeroLogContext
  pkg/log/kzerolog/kzerolog.go
Labels: backport

#615 Automated backport of #603: Fix data race in zeroLogContext
  pkg/log/kzerolog/kzerolog.go
Labels: ready-to-test, automated-backport
